In [203]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [204]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [205]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9425925925925925

In [206]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.29444444444444445

In [207]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9722222222222222

In [208]:
# -----------------KFold cross validation --------------------
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [209]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [210]:
#  ----------------------- Use KFold for our digits example -----------------
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [211]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [212]:

scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [213]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [214]:
scores_rf

[0.9215358931552587, 0.9449081803005008, 0.9315525876460768]

cross_val_score function


In [215]:
from sklearn.model_selection import cross_val_score

In [216]:
#---------------- Logistic regression model performance using cross_val_score -------------

cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [217]:
#-------------- svm model performance using cross_val_score---------------

cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [218]:
# -------------------- random forest performance using cross_val_score ----------

cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target,cv=3)

array([0.92988314, 0.94323873, 0.9148581 ])

Parameter tunning using k fold cross validation

In [219]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8809155803848542

In [220]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9354220980757294

In [221]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9454345127250157

In [222]:

scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9471198013656114

------------------- EXERXISE -------------------------

In [223]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.tree  import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score

In [224]:
iris = load_iris()

In [225]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [226]:
lr_score = cross_val_score(LogisticRegression(),iris.data,iris.target)
lr_score

c:\Users\tahur\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [227]:
np.average(lr_score)


0.9733333333333334

In [228]:

svm_score = cross_val_score(SVC(),iris.data,iris.target)
svm_score

# s_scores = cross_val_score(SVC(), iris.data, iris.target)
# s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [229]:
np.average(svm_score)

0.9666666666666666

In [230]:
tree_score =cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
tree_score

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [231]:
np.average(tree_score)

0.9666666666666668

In [234]:
ran_score =cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target)
ran_score

array([0.96666667, 0.96666667, 0.93333333, 0.9       , 1.        ])

In [235]:
np.average(ran_score)

0.9533333333333334